{{- if .Values.experimentalHttpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ include "gateway.fullname" . }}
    {{- if .Values.experimentalHttpRoute.inferenceGatewayNamespace }}
    namespace: {{ .Values.experimentalHttpRoute.inferenceGatewayNamespace }}
    {{- end }}
  rules:
  - backendRefs:
    - group: inference.networking.k8s.io
      kind: InferencePool
      name: {{ .Release.Name }}
    matches:
    - path:
        type: PathPrefix
        value: /
      {{- if or .Values.experimentalHttpRoute.baseModel .Values.experimentalHttpRoute.guideName }}
      headers:
      {{- if .Values.experimentalHttpRoute.baseModel }}
        - type: Exact
          name: X-gateway-base-model-name
          value: {{ .Values.experimentalHttpRoute.baseModel }}
      {{- end }}
      {{- if .Values.experimentalHttpRoute.guideName }}
        - type: Exact
          name: x-llm-d-guide-name
          value: {{ .Values.experimentalHttpRoute.guideName }}
      {{- end }}
      {{- end }}
    {{- if ne (lower .Values.provider.name) "gke" }}
    timeouts:
      request: {{ .Values.experimentalHttpRoute.requestTimeout }}
    {{- end }}
{{- end }}
